# Generated by Django 3.2 on 2021-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=24)),
                ('Apellido', models.CharField(max_length=24)),
                ('Edad', models.IntegerField()),
                ('Ciudad', models.CharField(max_length=20)),
            ],
        ),
    ]
